global:
  smtp_smarthost: ''  # Serveur SMTP (ex: smtp.gmail.com:587)
  smtp_from: ''  # Email de l'expéditeur
  smtp_auth_username: '' # Identifiant SMTP
  smtp_auth_password: ''       
  smtp_require_tls: true                

route:
  receiver: default-receiver

receivers:
- name: default-receiver
  email_configs:
  - to: "bentani.amin2000@gmail.com"