services:
  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./rules:/etc/prometheus/rules
    ports:
      - 9090:9090
    environment:
    - NODE_ENV=development
    - PORT=9090

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
    - NODE_ENV=development
    - PORT=3000

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command: 
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave